### ISSUE TITLE
Faros Not Reading XML File

### ISSUE THREAD

**Issue by GagePielsticker** [faros-ai/faros-test-results-reporter#14]
In our github action we are receiving `Error: EISDIR: illegal operation on a directory, read` when runnning `Report to FarosAI` step. The junity file exist within that directory as a .xml.

```yaml
name: Coverage-Reporting

on:
  push:
    branches:
      - 'develop'
      - 'qa'
      - 'main'
    
jobs:
  build:
    name: Test Coverage Report
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["18.x"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node Dependencies
        run: |
          npm ci

      - name: Installing Faros & Faros Dependencies
        run: |
          gh repo clone faros-ai/faros-test-results-reporter
          cd faros-test-results-reporter
          npm i
          cd ../
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Running Test
        run: |
          TEST_START=$(date -u "+%Y-%m-%dT%H:%M:%SZ")
          npm run test > /dev/null
          TEST_END=$(date -u "+%Y-%m-%dT%H:%M:%SZ")

      - name: Report to FarosAI
        run: |
          cd faros-test-results-reporter
          mv ../test-results.xml ./test-results.xml

          ./bin/main ./test-results.xml -k $FAROS_TOKEN --format junit \
            --commit GitHub://xxxxxxx/xxxxxxxxx/commit/${{ github.sha }} \
            --test-type Unit \
            --test-source Github \
            --test-start "$TEST_START" \
            --test-end "$TEST_END" \  
            --graph default \
            
        env:
          FAROS_TOKEN: ${{secrets.FAROS_KEY}}
      

      # - name: PUSH UNIT TEST
      #   run: |
      #     npm run test
```

Full error output
```
 [15:34:03.955] ERROR (1696): Processing failed. Error: EISDIR: illegal operation on a directory, read
    err: {
      "type": "Error",
      "message": "EISDIR: illegal operation on a directory, read",
      "stack":
          Error: EISDIR: illegal operation on a directory, read
              at Object.readSync (node:fs:744:3)
              at tryReadSync (node:fs:444:20)
              at Object.readFileSync (node:fs:490:19)
              at getJsonFromXMLFile (/home/runner/work/Atom-Search/Atom-Search/faros-test-results-reporter/node_modules/test-results-parser/src/helpers/helper.js:74:18)
              at Object.parse (/home/runner/work/Atom-Search/Atom-Search/faros-test-results-reporter/node_modules/test-results-parser/src/parsers/junit.js:207:16)
              at Object.parse (/home/runner/work/Atom-Search/Atom-Search/faros-test-results-reporter/node_modules/test-results-parser/src/parsers/index.js:65:27)
              at parse (/home/runner/work/Atom-Search/Atom-Search/faros-test-results-reporter/node_modules/test-results-parser/src/index.js:4:17)
              at TestResultsReporter.process (/home/runner/work/Atom-Search/Atom-Search/faros-test-results-reporter/lib/test-results-reporter.js:44:57)
              at Command.<anonymous> (/home/runner/work/Atom-Search/Atom-Search/faros-test-results-reporter/lib/index.js:70:80)
              at Command.listener [as _actionHandler] (/home/runner/work/Atom-Search/Atom-Search/faros-test-results-reporter/node_modules/commander/lib/command.js:482:17)
      "errno": -21,
      "syscall": "read",
      "code": "EISDIR"
    }
    ```
